language: node_js
node_js:
- 8.9.4
branches:
  only:
  - master
services:
- docker
before_script: 
script:
- npm i
- npm run build
deploy:
  provider: firebase
  token:
    secure: "i6ZFTuwYub/wh2g+hqYuUEVCMiVRSNG2CGqpl0yUEjCxA1/LKzv8iUEmZoczTk3427Yg2Wd1l1hqPKz6yZo3s2EfpyOHxDvxtImLT3BGW7WXZLjuZx4Uxsc+9lI1x2JzQP1C0neR5Xoar8LNMN1NB1k+IvJtTYjjsdrX2dp5NHV2i2eaRq/ega6+0evenQcPaMwa5sXk9keWo3buvz7A6iO5G+LbHh5mR/riwWv50kDP/FOFxNkaebIG8d8d5gNqp81NGUI+vlERj4sLQfaUD9wWXMPDgfUps4aIVwzQOfV5VPUTUipeSuj6aszqaxgMwsiOWYLWlDOxyr/ngAW5vnK3rKYU9mkJuH4SjaKoDVXsfmpfC8NvmHeDaajo38elfq7h5RVULEFxILvl6js2hcE5wLOaVUKLe+XCz1k995rqJjHJOLAqaogL50p+ZFDpsim4/z0EGRFaI1KBFAX3SS0NXSQeAqNB7fw+7NTq8jm4vx6qPq/dvXGznFa+V0qkWA87WkvT780xKgC3m+iOflIbyI0A3jXz9rgmewqvg2d46mqWSHncyOt4vmuNEkZy8WmC0+WmyJCHwDdKDnkJ0dk6pWuYdwqMJ7ERhZSSZQz9JdUQkj9fRUrUgnyk4dz75sgQkMEKJtoEdymWAvVHKJ39E4npIhQGmoCoYVS8XJE="
  local_dir: dist
  skip-cleanup: true
  project: blockexplore
  keep-history: true
  on:
    branch: master
env:
  global:
    secure: i6ZFTuwYub/wh2g+hqYuUEVCMiVRSNG2CGqpl0yUEjCxA1/LKzv8iUEmZoczTk3427Yg2Wd1l1hqPKz6yZo3s2EfpyOHxDvxtImLT3BGW7WXZLjuZx4Uxsc+9lI1x2JzQP1C0neR5Xoar8LNMN1NB1k+IvJtTYjjsdrX2dp5NHV2i2eaRq/ega6+0evenQcPaMwa5sXk9keWo3buvz7A6iO5G+LbHh5mR/riwWv50kDP/FOFxNkaebIG8d8d5gNqp81NGUI+vlERj4sLQfaUD9wWXMPDgfUps4aIVwzQOfV5VPUTUipeSuj6aszqaxgMwsiOWYLWlDOxyr/ngAW5vnK3rKYU9mkJuH4SjaKoDVXsfmpfC8NvmHeDaajo38elfq7h5RVULEFxILvl6js2hcE5wLOaVUKLe+XCz1k995rqJjHJOLAqaogL50p+ZFDpsim4/z0EGRFaI1KBFAX3SS0NXSQeAqNB7fw+7NTq8jm4vx6qPq/dvXGznFa+V0qkWA87WkvT780xKgC3m+iOflIbyI0A3jXz9rgmewqvg2d46mqWSHncyOt4vmuNEkZy8WmC0+WmyJCHwDdKDnkJ0dk6pWuYdwqMJ7ERhZSSZQz9JdUQkj9fRUrUgnyk4dz75sgQkMEKJtoEdymWAvVHKJ39E4npIhQGmoCoYVS8XJE=
